### ISSUE TITLE
Better handling of "multi-action" views

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/django-tutelary#12]
If you have something like a DRF `ListCreateAPIView`, how do you permission it?  The GET handler is for listing objects, the POST handler for creating them.  Perhaps the `permission_required` attribute in `PermissionRequiredMixin` should take a dictionary mapping HTTP methods to permissions?

**Comment by oliverroick** [comment]
For organisations API views, I had to implement a Django Rest Framework specific `PermissionRequiredMixin`, because permission verification is different in DRF. The mixin also handles permissions for multi-action views ([mixin code](https://github.com/Cadasta/cadasta-platform/blob/feature/organizations/cadasta/core/views.py#L35)). 

Usage:

```python
class OrganisationList(APIVIew):
    permission_required = {
        'GET': 'org.list',
        'POST': 'org.create'
    }
```

**Comment by ian-ross** [comment]
Here, I'm going to pull the permissions features that @oliverroick has implemented in  https://github.com/Cadasta/cadasta-platform/pull/64 into django-tutelary, adding some additional options to the `actions` attribute for permissioned models and the `permission_required` attribute in the `PermissionsRequiredMixin`.
