### ISSUE TITLE
Combining org.list and org.view when evaluating permissions

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/django-tutelary#13]
Consider the following use case:

There are two organisations and a user is allowed to only access one of them. When that user requests the list of organisations, the response should only contain one organisation. It seems, that `org.view` permissions are not evaluated when requesting  a list of organisations.

I tried with the following policy:

```json
 {
    "clause": [{
        "effect": "allow",
        "object": ["*"],
        "action": ["org.list"]
    }, {
        "effect": "allow",
        "object": ["organization/*"],
        "action": ["org.view"]
    }, {
        "effect": "deny",
        "object": ["organization/unauthorized"],
        "action": ["org.view"]
    }]
}
```

**Comment by ian-ross** [comment]
We should talk about how this could work.  I've added some stuff to work with "collective actions", which is to do with the fact that, for example, your `org.list` action doesn't refer to any particular organisation, but is a collective action on all organisations (and similarly, if projects belong to organisations, then `project.list` is a collective action on all projects within an organisation, not on any individual project).  This interaction between "individual" and "collective" actions seems like it's somehow related to that.

**Comment by ian-ross** [comment]
So, following discussions with @oliverroick, I think there are two related but separate issues here:

1. It should be possible for a view to specify that, if it's a collective action (e.g. listing all the items in a collection), and the appropriate permissions aren't allowed for all items in the collection, then the result should not be a single "permission denied" exception (as is currently the case), but the view's queryset should be filtered to include only the objects for which the relevant permissions are allowed.

2. In the particular case of listing a collection of items, it may be desirable to further filter the view's queryset so that only objects for which the user has additional permissions are included.  To be specific, if we have a general `thing.list` permission for listing the existence of some class of object, and a `thing.view` permission for viewing the details of individual objects, we may only wish for a list view to show objects for which the user has the additional detail view permission.

Both of these features can be implemented without too much difficulty, I think.
